name: 'trino_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'trino_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  trino_pipeline:
    # Applies to all files under models/staging/
    staging:
      +materialized: view
    # Applies to all files under models/marts/
    marts:
      +materialized: table
      +properties:
        format: "'PARQUET'"